### ISSUE TITLE
Add node_modules to .gitignore

### ISSUE THREAD

**Issue by manojna191** [samrat2k03/JuJu-Dating-WebSite#6]
Proposing to add node_modules of server folder to the .gitignore for improved project efficiency:

1. Repository Size and Speed:
Excluding node_modules reduces repository size, speeding up cloning and pulling.

2. Reproducibility:
Ensures easy project setup for contributors using npm install or yarn install.

3. Avoiding Conflicts:
Prevents conflicts across different environments.

4. Focus on Code:
Maintains a clean repository, focusing on essential code.

5. Security and Licensing:
Avoids sharing sensitive information and respects licensing.

Proposed Change:
Add node_modules/ to the .gitignore file.

Expected Impact:

Smaller repository size.
Faster cloning and pulling.
Improved development environment consistency.
Reduced potential conflicts.
Cleaner, more focused repository.

**Comment by manojna191** [comment]
Please assign the issue to me @samrat2k03

**Comment by samrat2k03** [comment]
start working, mate
